version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
skip_commits:
  message: /.*\[ci\-skip\].*/ 
before_build:
- cmd: dotnet restore src/Vlingo.Common.sln
build:
  project: src/Vlingo.Common.sln
  verbosity: normal
  publish_nuget: true
test_script:
- cmd: dotnet test src/Vlingo.Common.Tests
deploy:
- provider: NuGet
  api_key:
    secure: 6PolwOKBEDVJni+GK7a1YHoXCA708qROXjfMy4myXtpa/RGTIgP7dCDLlcQxz/YA
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/2b56d1ca84637acb9ee8
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true